Remove hard-coded Gerrit statuses
The statuses can be extended via Gerrit plugins, in which case we
would throw an exception and fail to show any changes for the issue.

java.lang.IllegalArgumentException: No enum constant com.meetme.plugins.jira.gerrit.data.dto.GerritChange.Status.INTEGRATING
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.meetme.plugins.jira.gerrit.data.dto.GerritChange$Status.valueOf(GerritChange.java:35)
	at com.meetme.plugins.jira.gerrit.data.dto.GerritChange.fromJson(GerritChange.java:90)
	at com.sonyericsson.hudson.plugins.gerrit.gerritevents.dto.attr.Change.<init>(Change.java:97)
	at com.meetme.plugins.jira.gerrit.data.dto.GerritChange.<init>(GerritChange.java:52)
	at com.meetme.plugins.jira.gerrit.data.IssueReviewsImpl.getReviewsFromGerrit(IssueRev

There's no need to hard-code these statuses as enums, as the rest
of the plugin operates on them as strings anyways.